title: xzm's homepage
email: your-email@example.com
description: >-
  Ziming Xian's hardware engineering portfolio.
baseurl: ""
url: "https://zimingxian.github.io"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - serve-local.bat
  - package-offline.bat
  - package-offline.ps1
  - jekyll-server.out.log
  - jekyll-server.err.log
  - portfolio-offline.zip
  - .sass-cache
